# Disable all non-key authentication
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
KerberosAuthentication no
GSSAPIAuthentication no
PasswordAuthentication no

PubkeyAuthentication yes
AuthenticationMethods publickey
PermitRootLogin no

PrintMotd no
PrintLastLog no
MaxSessions 5
MaxStartups 5:10:50
